In [1]:
import tensorflow as tf

2025-01-09 19:23:38.285775: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
add1 = tf.constant(1,dtype=tf.int32,shape=[2,3,4])
add2 = tf.constant(-1, dtype=tf.int32, shape=[4])

In [3]:
add1 + add2

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)>

In [4]:
add3 = tf.constant(-1, dtype=tf.int32, shape=[3,4])
add1 + add3

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)>

In [5]:
add4 = tf.constant(-1, dtype=tf.int32, shape=[2,1,4])
add1 + add4

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)>