In [1]:
import tensorflow as tf

2025-01-13 15:11:24.409609: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
input = tf.constant([[
    1,2,3
],[
    4,5,6
]], dtype=tf.float32)
input

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [3]:
tf.reduce_sum(input_tensor=input, axis=0)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([5., 7., 9.], dtype=float32)>

In [4]:
tf.reduce_sum(input, axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 6., 15.], dtype=float32)>

In [5]:
tf.reduce_sum(input, axis=[0,1])

<tf.Tensor: shape=(), dtype=float32, numpy=21.0>

In [6]:
input2 = tf.reshape(tf.range(12, dtype=tf.float32), [2,2,3])
input2

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>

In [7]:
tf.reduce_sum(input2, axis=1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 3.,  5.,  7.],
       [15., 17., 19.]], dtype=float32)>

tf.reduce_sum的计算规则，axis=i：
- shape：消除第i维，更高维、低维的shape都不变
- 遍历第i-1维，对每个单元内的第i维的元素纵向堆叠求和，导致第i维消失