In [1]:
import tensorflow as tf

2025-01-13 15:37:39.277710: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


tensor_scatter_nd_add 在tensor的indices位置上加updates

In [2]:
x = tf.constant([[1,2,3],[4,5,6]], dtype=tf.float32)
indices = tf.constant([[0,0],[1,1]])
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [5]:
updater = tf.constant([9,9],dtype=tf.float32)
tf.tensor_scatter_nd_add(tensor=x,indices=indices, updates=updater)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[10.,  2.,  3.],
       [ 4., 14.,  6.]], dtype=float32)>