In [1]:
import tensorflow as tf

2025-01-09 20:11:23.346070: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
x = tf.reshape(tf.range(24), [2,3,4])
x

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]], dtype=int32)>

In [3]:
tf.transpose(x, perm=[0,2,1])

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]], dtype=int32)>

In [4]:
y = tf.reshape(tf.range(24), [2,2,3,2])
y

<tf.Tensor: shape=(2, 2, 3, 2), dtype=int32, numpy=
array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]]], dtype=int32)>

In [5]:
tf.transpose(y, perm=[0, 2, 1, 3]) # 变化的是第1、2维度，把第3维视为一个整体/原子

<tf.Tensor: shape=(2, 3, 2, 2), dtype=int32, numpy=
array([[[[ 0,  1],
         [ 6,  7]],

        [[ 2,  3],
         [ 8,  9]],

        [[ 4,  5],
         [10, 11]]],


       [[[12, 13],
         [18, 19]],

        [[14, 15],
         [20, 21]],

        [[16, 17],
         [22, 23]]]], dtype=int32)>